### ISSUE TITLE
Bug nella selezione del sistema operativo

### ISSUE THREAD

**Issue by UserRoot-Luca** [MinerAle00/vmbuilder#10]
Lo script non ti permette di selezionare altri sistemi operativi al di fuori del primo

![bug](https://github.com/MinerAle00/vmbuilder/assets/55756898/f6e74878-6504-4931-b1e3-f6a6484c2a46)

**Comment by MinerAle00** [comment]
Ciao, dovrei aver fixato il problema. Prova a scaricare la nuova versione, mi raccomando cambia il branch che non è ancora in main ora.
